name: Automerge
on:
  push:
    branches: [ "feature/**", "hotfix/**" ]
  pull_request:
    branches: [ "feature/**", "hotfix/**" ]

jobs:
  build-and-test-local:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci

  build-and-test-develop:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci

  merge-to-develop:
    name: Merge local branch to develop
    needs: [ build-and-test-local, build-and-test-develop ]
    runs-on: ubuntu-latest
    steps:
      - name: Merge local branch to develop
        if: contains(github.event.head_commit.message, '[MERGE2DEVELOP]') ||
            contains(github.event.head_commit.message, '[MERGE2DEV]')
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop