name: Automerge
on:
  push:
    branches: [ "feature/**", "hotfix/**" ]
  pull_request:
    branches: [ "feature/**", "hotfix/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: test action
      uses: colbyhill21/angular-full-ci/@v1.0
      with:
        node-version: ${{ matrix.node-version }}
        testcommand: run test:ci